name: ❤️ Greetings

on:
  issues:
    types: [opened]
  pull_request_target:
    branches: [master]
    types: [opened]

jobs:
  greet:
    name: Greet New Contributors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            Thank you for your first ever contribution to [roadmap.sh](https://roadmap.sh)! 🎉
            
            Please make sure to follow the [contribution guidelines](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md) when contributing to this project. Any PRs that don't follow the guidelines will be closed.

            Thanks for choosing to contribute, and for helping make this project better! 🌟